# Generated by Django 3.1.3 on 2024-02-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0007_auto_20240220_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='setting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='manage_tournament.matchsetting'),
        ),
    ]
