# Generated by Django 5.0 on 2023-12-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
