# Generated by Django 5.0 on 2023-12-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
