# Generated by Django 5.0 on 2023-12-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.jpeg', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='intra_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='playername',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
