# Generated by Django 3.1.3 on 2023-12-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameHistory_microservice', '0001_initial'),
        ('account', '0017_auto_20231220_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_game_stats', to='gameHistory_microservice.gamestats'),
        ),
    ]
