# Generated by Django 3.1.3 on 2024-01-10 21:31

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchparticipants',
            old_name='participant_sacore',
            new_name='participant_score',
        ),
    ]
