# Generated by Django 5.0.1 on 2024-03-27 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_base_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_valid_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
