# Generated by Django 5.0.1 on 2024-03-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_base_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('', 'Off'), ('sms', 'SMS'), ('email', 'Email')], default='', max_length=10, null=True),
        ),
    ]
