# Generated by Django 5.0.1 on 2024-03-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='email', max_length=10),
        ),
    ]
