# Generated by Django 5.0.1 on 2024-03-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_two_factor_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), (None, 'Turn Off')], default=None, max_length=10),
        ),
    ]
