# Generated by Django 5.0.1 on 2024-03-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_two_factor_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[(None, 'Off'), ('sms', 'SMS'), ('email', 'Email')], default='', max_length=10, null=True),
        ),
    ]
