<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-03-31 11:06
=======
# Generated by Django 5.0.1 on 2024-03-31 14:20
>>>>>>> 73e55d78eb77c642a52ef61847da7ef2ef926d73

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_two_factor_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[(None, 'Off'), ('sms', 'SMS'), ('email', 'Email')], default='', max_length=10, null=True),
        ),
    ]
