# Generated by Django 5.0.1 on 2024-03-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_valid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
