# Generated by Django 5.0 on 2023-12-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='default_avatar.jpeg', max_length=255, null=True),
        ),
    ]
