# Generated by Django 3.1.3 on 2023-12-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20231217_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamenthistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameStats',
        ),
        migrations.DeleteModel(
            name='TournamentHistory',
        ),
    ]
