# Generated by Django 5.0.1 on 2024-01-20 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(default=1, max_length=100, unique=True)),
                ('winner', models.CharField(blank=True, max_length=15, null=True)),
                ('number_of_players', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=15, null=True)),
                ('total_games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.PositiveIntegerField()),
                ('player1', models.CharField(blank=True, max_length=15, null=True)),
                ('player2', models.CharField(blank=True, max_length=15, null=True)),
                ('date_played', models.DateField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameHistory_microservice.tournamenthistory')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
