# Generated by Django 3.1.3 on 2023-12-27 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameHistory_microservice', '0002_gamestats_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamenthistory',
            name='date_played',
        ),
        migrations.RemoveField(
            model_name='tournamenthistory',
            name='result',
        ),
        migrations.RemoveField(
            model_name='tournamenthistory',
            name='tournament_name',
        ),
        migrations.RemoveField(
            model_name='tournamenthistory',
            name='user',
        ),
        migrations.AddField(
            model_name='tournamenthistory',
            name='number_of_players',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamenthistory',
            name='tournament_id',
            field=models.CharField(default=1, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tournamenthistory',
            name='winner',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.PositiveIntegerField()),
                ('player1', models.CharField(blank=True, max_length=15, null=True)),
                ('player2', models.CharField(blank=True, max_length=15, null=True)),
                ('date_played', models.DateField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameHistory_microservice.tournamenthistory')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
