# Generated by Django 5.0.1 on 2024-01-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameHistory_microservice', '0005_auto_20231230_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamenthistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
