# Generated by Django 3.1.3 on 2023-12-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameHistory_microservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
