# Generated by Django 3.1.3 on 2024-02-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MatchSetting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration_sec', models.IntegerField(default=210)),
                ('max_score', models.IntegerField(default=5)),
                ('nbr_of_sets', models.IntegerField(default=1)),
                ('paddle_speed', models.IntegerField(default=10)),
                ('ball_speed', models.IntegerField(default=10)),
                ('nbr_of_players', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('player_id', 'username')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nbr_of_player', models.IntegerField(default=2)),
                ('registration_period_min', models.IntegerField(default=15)),
                ('host_id', models.IntegerField()),
                ('game_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manage_tournament.gametype')),
                ('registration', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manage_tournament.registrationtype')),
                ('setting', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manage_tournament.matchsetting')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('match_time', models.DateTimeField(null=True)),
                ('match_result', models.CharField(max_length=255)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='manage_tournament.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manage_tournament.tournamenttype'),
        ),
        migrations.CreateModel(
            name='MatchParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(default=False)),
                ('participant_score', models.IntegerField(default=0)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='manage_tournament.tournamentmatch')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playeridfrommatch', to='manage_tournament.player')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='manage_tournament.player')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='manage_tournament.tournament')),
            ],
            options={
                'unique_together': {('tournament_id', 'player')},
            },
        ),
    ]
