# Generated by Django 5.0.3 on 2024-03-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='participants',
        ),
    ]
