# Generated by Django 5.0.3 on 2024-03-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('Knockout', 'Knock Out'), ('League', 'Round Robin')], default='tournament', max_length=15),
        ),
    ]
