# Generated by Django 5.0.3 on 2024-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0002_alter_tournament_tournament_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('Knock-out', 'Knock-Out'), ('League', 'Round Robin')], default='Knock-out', max_length=15),
        ),
    ]
