# Generated by Django 5.0.3 on 2024-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0002_remove_tournamentmatch_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='participants',
            field=models.ManyToManyField(related_name='matches', to='manage_tournament.matchparticipants'),
        ),
    ]
