# Generated by Django 5.0.3 on 2024-03-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0002_alter_tournament_tournament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='state',
            field=models.CharField(default='waiting', max_length=15),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='state',
            field=models.CharField(default='waiting', max_length=15),
        ),
    ]
