# Generated by Django 5.0.3 on 2024-03-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0002_alter_tournament_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='registration',
        ),
    ]
