# Generated by Django 5.0.3 on 2024-03-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0002_remove_tournament_game_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchparticipants',
            name='participant_score',
        ),
    ]
