# Generated by Django 5.0.3 on 2024-03-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0003_remove_tournament_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='game_type',
        ),
    ]
