# Generated by Django 3.1.3 on 2024-01-11 17:34

from django.db import migrations

def add_tournament_types(apps, schema_editor):
    TournamentType = apps.get_model('manage_tournament', 'TournamentType')
    TournamentType.objects.create(type_name='single-elimination tournament')
    TournamentType.objects.create(type_name='double-elimination tournament')
    TournamentType.objects.create(type_name='best-of-n series')

class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0003_auto_20240111_1719'),
    ]

    operations = [
        migrations.RunPython(add_tournament_types),
    ]
