# Generated by Django 5.0.3 on 2024-03-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0003_remove_matchparticipants_participant_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
