# Generated by Django 5.0.3 on 2024-04-01 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0004_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='participants',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to='manage_tournament.player'),
        ),
        migrations.AlterField(
            model_name='matchsetting',
            name='paddle_speed',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01, message='Paddle speed must be at least 0.1.'), django.core.validators.MaxValueValidator(2, message='Paddle speed cannot exceed 2.')]),
        ),
        migrations.AlterField(
            model_name='matchsetting',
            name='walls_factor',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=3, validators=[django.core.validators.MinValueValidator(0, message='Walls factor must be at least 0.'), django.core.validators.MaxValueValidator(2, message='Walls factor cannot exceed 2.')]),
        ),
    ]
