# Generated by Django 5.0.3 on 2024-03-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0004_alter_tournament_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
