# Generated by Django 3.1.3 on 2024-01-11 18:01

from django.db import migrations

def add_resgistration_types(apps, schema_editor):
    RegistrationType = apps.get_model('manage_tournament', 'RegistrationType')
    RegistrationType.objects.create(type_name='open')

class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0004_auto_20240111_1734'),
    ]

    operations = [
        migrations.RunPython(add_resgistration_types),
    ]
