# Generated by Django 5.0.3 on 2024-03-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0004_remove_tournament_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_type',
        ),
    ]
