# Generated by Django 5.0.4 on 2024-04-05 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0005_remove_tournamentmatch_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsetting',
            name='ball_model',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='matchsetting',
            name='ball_texture',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='matchsetting',
            name='nbr_of_rounds',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='matchsetting',
            name='ball_color',
            field=models.CharField(default='0x000000', max_length=8, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', message='Invalid color format.')]),
        ),
    ]
