# Generated by Django 5.0.3 on 2024-03-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0005_remove_tournament_tournament_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='tournament_id',
            field=models.IntegerField(),
        ),
    ]
