# Generated by Django 3.1.3 on 2024-01-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0005_auto_20240111_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manage_tournament.gametype'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manage_tournament.registrationtype'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='setting_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manage_tournament.matchsetting'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manage_tournament.tournamenttype'),
        ),
    ]
