# Generated by Django 3.1.3 on 2024-02-20 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0006_auto_20240218_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manage_tournament.matchsetting'),
        ),
    ]
