# Generated by Django 5.0.3 on 2024-03-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0006_alter_tournamentmatch_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='match_setting_id',
            field=models.IntegerField(),
        ),
    ]
