# Generated by Django 5.0.3 on 2024-03-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0007_alter_tournamentmatch_match_setting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchparticipants',
            name='match_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matchparticipants',
            name='player_id',
            field=models.IntegerField(),
        ),
    ]
