# Generated by Django 5.0.4 on 2024-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0008_remove_tournament_tournament_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchsetting',
            name='ball_model',
            field=models.CharField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='matchsetting',
            name='ball_texture',
            field=models.CharField(default='', null=True),
        ),
    ]
