# Generated by Django 5.0.3 on 2024-03-18 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0008_alter_matchparticipants_match_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_participants', to='manage_tournament.matchparticipants'),
        ),
    ]
