# Generated by Django 5.0.4 on 2024-04-12 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0009_alter_matchsetting_ball_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchsetting',
            name='ball_speed',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.09, message='Ball speed must be at least 0.1.'), django.core.validators.MaxValueValidator(2, message='Ball speed cannot exceed 2.')]),
        ),
    ]
