# Generated by Django 5.0.3 on 2024-03-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tournament', '0009_alter_tournamentmatch_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchparticipants',
            name='player_id',
            field=models.IntegerField(null=True),
        ),
    ]
